### PR TITLE
Better error reporting in makeCopySqlite

### LINKED ISSUE #139: Error reporting in makeCopySqlite
A couple of related issues:

     - error from sqlite is not passed to the exception -> no detailed info when exception is raised
     - Sqlite3Db::create() should provide more info about the error
     - GEODIFF_makeCopySqlite() does not say what is the problem when opening/creating
     - GEODIFF_makeCopySqlite() should report if it deletes a DB file (and if it was successful)
     - GEODIFF_makeCopySqlite() should maybe first try to open it as SQLite, only then remove it

### PR DESCRIPTION
**Pull request by wonder-sk**
Fixes #139

### CODE REVIEW

File: geodiff/src/drivers/sqliteutils.cpp [hunk 1]
```diff
@@ -31,7 +31,10 @@ void Sqlite3Db::open( const std::string &filename )
   int rc = sqlite3_open_v2( filename.c_str(), &mDb, SQLITE_OPEN_READWRITE, nullptr );
   if ( rc )
   {
-    throw GeoDiffException( "Unable to open " + filename + " as sqlite3 database" );
+    std::string errMsg;
+    if ( mDb )
+      errMsg = sqlite3_errmsg( mDb );
+    throw GeoDiffException( "Unable to open " + filename + " as sqlite3 database (" + errMsg + ")" );
```
Comment (PeterPetrik) [inline geodiff/src/drivers/sqliteutils.cpp:37]: suggestion: 
if `mDB==0` then the error is for example `Unable to open myfile.gpkg as sqlite3 database ()`, maybe add unknown error or just omit bracket?

File: geodiff/src/drivers/sqliteutils.cpp [hunk 2]
```diff
@@ -47,7 +50,10 @@ void Sqlite3Db::create( const std::string &filename )
   int rc = sqlite3_open_v2( filename.c_str(), &mDb, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, nullptr );
   if ( rc )
   {
-    throw GeoDiffException( "Unable to create " + filename + " as sqlite3 database" );
+    std::string errMsg;
+    if ( mDb )
+      errMsg = sqlite3_errmsg( mDb );
+    throw GeoDiffException( "Unable to create " + filename + " as sqlite3 database (" + errMsg + ")" );
```
Comment (PeterPetrik) [inline geodiff/src/drivers/sqliteutils.cpp:56]: suggestion: 
if `mDB==0` then the error is for example `Unable to open myfile.gpkg as sqlite3 database ()`, maybe add unknown error or just omit bracket?

File: geodiff/src/geodiff.cpp [hunk 3]
```diff
@@ -688,7 +688,11 @@ int GEODIFF_makeCopySqlite( const char *src, const char *dst )
   // gets overwritten, regardless of its original content (making the API easier to use for the caller).
   if ( fileexists( dst ) )
   {
-    fileremove( dst );
+    Logger::instance().warn( "MakeCopySqlite: Removing existing destination database: " + std::string( dst ) );
```
Comment (PeterPetrik) [inline geodiff/src/geodiff.cpp:691]: suggestion: 

cannot we move it to `else` branch so in the logs you have either "failed to remove ..." or "removed ..." sentence?

**Review by PeterPetrik — APPROVED** [review]
