### PR TITLE
Fix handling of rebase when editors change the same value

### LINKED ISSUE #152: Rebase creates conflict if both "our" and "their" changeset do the same change
As the title says - if two users do an update of a feature independently, but the actual change is the same (e.g. both change an attribute value of the same feature from 40 to 42), geodiff will generate a rebase conflict file. Ideally this should not happen, because there wasn't really any conflict, so we should detect such cases and skip reporting conflicts, because that's confusing to users if they see conflict files appearing.

Try to run this command using test data from geodiff:
```
$ geodiff rebase-diff tests/testdata/base.gpkg \
    tests/testdata/1_geopackage/base-modified_1_geom.diff \
    tests/testdata/1_geopackage/base-modified_1_geom.diff \
    /tmp/x_rebased.diff /tmp/x_conflict.json
```

In short, we are trying to rebase a diff on top of the same diff, so there should be no conflict and the rebased diff should be empty. But instead we are getting a conflict file:

```
{
   "geodiff": [
      {
        "table": "gpkg_contents",
        "type": "conflict",
        "fid": "334167370",
        "changes": [
          {
              "column": 5,
              "base": -1.0889200000000001,
              "old": -0.73050599999999999,
              "new": -0.73050599999999999
          }
        ]
      },
      {
        "table": "simple",
        "type": "conflict",
        "fid": "1",
        "changes": [
          {
              "column": 1,
              "base": "R1AAAeYQAAABAQAAAB54y6E2bPG/cOaqyDmB3T8=",
              "old": "R1AAAeYQAAABAQAAAClvCOFAFeG/lhl3A7Qi0z8=",
              "new": "R1AAAeYQAAABAQAAAClvCOFAFeG/lhl3A7Qi0z8="
          }
        ]
      }
   ]
}
```
(the gpkg_contents changes should have been ignored when reading the source diff, that's probably another minor issue to handle)

And the rebased diff looks like this instead of being empty:
```
{
   "geodiff": [
      {
        "table": "gpkg_contents",
        "type": "update",
        "changes": [
          {
              "column": 0,
              "old": "simple"
          },
          {
              "column": 4,
              "old": "2019-06-26T08:19:00.735Z",
              "new": "2019-06-26T08:19:00.735Z"
          },
          {
              "column": 5,
              "old": -0.73050599999999999,
              "new": -0.73050599999999999
          }
        ]
      },
      {
        "table": "simple",
        "type": "update",
        "changes": [
          {
              "column": 0,
              "old": 1
          },
          {
              "column": 1,
              "old": "R1AAAeYQAAABAQAAAClvCOFAFeG/lhl3A7Qi0z8=",
              "new": "R1AAAeYQAAABAQAAAClvCOFAFeG/lhl3A7Qi0z8="
          }
        ]
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by wonder-sk**
When the final value (of a given row in a given column) would end up the same after two concurrent edits, geodiff would still produce conflicts, confusing users why would they appear. This commit adds handling of that case.

Fixes #152

### CODE REVIEW

File: geodiff/src/geodiffrebase.cpp [hunk 1]
```diff
@@ -463,31 +463,46 @@ bool _handle_update( const ChangesetEntry &entry, const RebaseMapping &mapping,
...
     }
     else
     {
-      // otherwise the value is same for both patched and this, so use base value
+      // the "new" changeset stays as is without modifications
       outEntry.oldValues[i] = entry.oldValues[i];
+      outEntry.newValues[i] = entry.newValues[i];
+      // if a column is pkey, it would have "new" value undefined in the entry and that's not an actual change
+      if ( entry.newValues[i].type() != Value::TypeUndefined )
+        entryHasChanges = true;
```
Comment (tomasMizera) [inline geodiff/src/geodiffrebase.cpp:497]: Isn't this `else` covering three cases?:
 1. both old and new values are null -> no change
 2. old value is null and new value is not -> change, covered
 3. old value is not null and new value is null -> should result to change, but is not?

**Review by tomasMizera — APPROVED** [review]
